#!mainFile "main.opy"

rule "Map Data - Example":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.HANAMURA
    @Delimiter

	# Checkpoints = [vect(66.293, 0.681, 13.266), vect(51.871, 0.474, 12.835), vect(38.727, 0.789, 10.979), vect(34.831, 1.206, 2.953), vect(28.592, 1.641, -4.084)]
	# RingSize = 2.5
	# CreatorName = "DragonEngineer"
	# MapCode = "ABCDE"

